'use strict';

const chalk           = require('chalk');
const inquirer        = require('inquirer');
const templatesList   = require('./list');
const story           = require('./stories');
const templatesRouter = require('./templates-router');
const createFile      = require('./utils/createFile');

let templateName;

Promise
  .resolve()
  .then(() => inquirer.prompt(templatesList))
  .then((t) => selectStory(t))
  .then((ans) => templatesRouter(templateName, ans))
  .then((arr) => createFile(arr))
  .then(() => console.log(chalk.cyan('finish!')))
  .catch((err) => console.error(chalk.red(err)));

/**
 * select the story
 * @param {Object} t - generated by inquirer
 * @return {Promise}
 */
function selectStory(t) {
  templateName = t.template;

  return inquirer.prompt(story[templateName]);
}
